name: Deploy

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  # deploy:
  #   runs-on: ubuntu-latest
  #   name: Deploy
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Deploy
  #       uses: cloudflare/wrangler-action@v3
  #       with:
  #         apiToken: ${{ secrets.CF_API_TOKEN }}
  #         accountId: ${{ secrets.CF_ACCOUNT_ID }}
      
  test-job:
    runs-on: ubuntu-latest
    name: TestJob
    steps: 
      - name: with set -x
        run: |
          set -x
          date
          hostname
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint:1.7.3
      - name: with out set -x
        run: |
          date
          hostname
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint:1.7.3
    